### ISSUE TITLE
签名验证失败

### ISSUE THREAD

**Issue by GaiJoon** [RevenueMonster/RM-API-SDK-PHP#7]
![image](https://user-images.githubusercontent.com/40667087/95319207-2ad5c200-08ca-11eb-9e79-514557dc63ea.png)
![image](https://user-images.githubusercontent.com/40667087/95319255-3cb76500-08ca-11eb-8c0a-9c6e7e2ae154.png)
我用示例代码验证失败

**Comment by GaiJoon** [comment]
求救

**Comment by si3nloong** [comment]
@GaiJoon 你的rm client设置对吗？

**Comment by GaiJoon** [comment]
您说的是这个吗
  $rm = new RevenueMonster([
            'clientId' =&gt; '1601977748853222158',
            'clientSecret' =&gt; 'YzTkhCPPoVgTvIMRiMYetsHwTccaWPFH',
//            'privateKey' =&gt; file_get_contents(__DIR__.'/private_key.pem'),
            'publicKey' =&gt; file_get_contents(__DIR__.'/public_key.pem'),
//            'publicKey' =&gt; self::private_key,
//            'version' =&gt; 'stable',
            'isSandbox' =&gt; false,
        ]);




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RevenueMonster/RM-API-SDK-PHP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月8日(星期四) 凌晨0:35
收件人:&nbsp;"RevenueMonster/RM-API-SDK-PHP"<RM-API-SDK-PHP@noreply.github.com&gt;;
抄送:&nbsp;"GaiJoon"<1923024862@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [RevenueMonster/RM-API-SDK-PHP] 签名验证失败 (#7)





 
@GaiJoon 你的rm client设置对吗？

**Comment by GaiJoon** [comment]
> @GaiJoon你的rm client设置对吗？
![Uploading image.png…]()

**Comment by GaiJoon** [comment]
![image](https://user-images.githubusercontent.com/40667087/95361042-caad4300-08fe-11eb-9c73-e733fefc3bfe.png)

**Comment by GaiJoon** [comment]
![image](https://user-images.githubusercontent.com/40667087/95361101-e1ec3080-08fe-11eb-8c5e-db81f50604a9.png)
我是在这设置拿的 私钥

**Comment by GaiJoon** [comment]
@si3nloong

**Comment by GaiJoon** [comment]
大神 您帮我看看  我有点着急

**Comment by si3nloong** [comment]
@GaiJoon 从你的照片链接看，我看到你的私匙落空。我们查了下，你的账号是生产环境对吧？

**Comment by GaiJoon** [comment]
对&nbsp; &nbsp;不过现在好用了&nbsp; 现在的问题是 支付完回调没好用

notifyUrl 我不知道你是怎么回调的 传的什么参数 怎么传的 post还是GET 收到请回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RevenueMonster/RM-API-SDK-PHP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月8日(星期四) 下午5:46
收件人:&nbsp;"RevenueMonster/RM-API-SDK-PHP"<RM-API-SDK-PHP@noreply.github.com&gt;;
抄送:&nbsp;"GaiJoon"<1923024862@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [RevenueMonster/RM-API-SDK-PHP] 签名验证失败 (#7)





 
@GaiJoon 从你的照片链接看，我看到你的私匙落空。我们查了下，你的账号是生产环境对吧？

**Comment by GaiJoon** [comment]
方便打个电话 或者加个微信 facebook也可以

**Comment by GaiJoon** [comment]
你好在吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RevenueMonster/RM-API-SDK-PHP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月8日(星期四) 下午5:46
收件人:&nbsp;"RevenueMonster/RM-API-SDK-PHP"<RM-API-SDK-PHP@noreply.github.com&gt;;
抄送:&nbsp;"GaiJoon"<1923024862@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [RevenueMonster/RM-API-SDK-PHP] 签名验证失败 (#7)





 
@GaiJoon 从你的照片链接看，我看到你的私匙落空。我们查了下，你的账号是生产环境对吧？

**Comment by GaiJoon** [comment]
现在我的&nbsp;notify-url 获取不到值 我是tp6框架&nbsp;

**Comment by si3nloong** [comment]
@GaiJoon 成功的交易才会发webhook。我们建议你设放一个cronjob来更新每个订单的状态。
